//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaStomPlusMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypeId { get; set; }
        public byte[] Content { get; set; }
        public int Status { get; set; }
    
        public virtual DocType DocType { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
