//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaStomPlusMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Appointment = new HashSet<Appointment>();
            this.Document = new HashSet<Document>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CardNumber { get; set; }
        public string FullName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int Sex { get; set; }
        public Nullable<int> PassportSerial { get; set; }
        public Nullable<int> PassportNumber { get; set; }
        public bool HasXray { get; set; }
        public bool HasInsurance { get; set; }
        public string Phone { get; set; }
        public int Status { get; set; }
        public bool XrayInClinic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Document { get; set; }
    }
}
